### ISSUE TITLE
Changing variables affects all apps on server

### ISSUE THREAD

**Issue by GAndrsn** [met-office-lab/model_evaluation_tool#1]
If two people have, for example, the model vs. model app open, and User1 changes the plotted variable in their app, then the current_var variable will change for all users, and so the next time the User2 makes any other change that updates the plot, e.g. time, the variable will also change to the one set by User1.

**Comment by GAndrsn** [comment]
Was this issue resolved, and can it be closed?

**Comment by stevehadd** [comment]
The problem was partly fixed by the commit referenced in this issue, but I wanted wait until the refactor was done to be sure that it was completely fixed. Now that's been done, I'm happy to close it.
