### ISSUE TITLE
Set app page titles

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#12]
The app titles do not appear as the title of the html page, so for example the tabs in a browser are not labelled other than bokeh application.

**Comment by GAndrsn** [comment]
This has been set up for the model vs GPM app by adding the following line at the end of the main.py script:

```bokeh.plotting.curdoc().title = 'Model rainfall vs GPM app' ```

**Comment by GAndrsn** [comment]
```bokeh.plotting.curdoc().title``` added to all other apps, should be applied on next server restart.

**Comment by GAndrsn** [comment]
Issue fixed.
