### ISSUE TITLE
Improve storage config of server

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#18]
We need to ensure that the server has sufficient space for the data it will be downloading to do the plotting, and ensure that storage is part of the EC2 instance rather than the docker container.

**Comment by AlexHilson** [comment]
Hiya - very true, but I wouldn't worry too much about the deployment. We're hoping to cover the deployment, resource allocation, scaling etc over at https://github.com/met-office-lab/dashboard-service

**Comment by stevehadd** [comment]
Based on Alex's comment and the fact that we're loading the data through goofys streaming, this issue is no longer relevant so I am closing the issue.
