### ISSUE TITLE
Code rationalisation

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#20]
Issue to plan what we want to achieve and keep track of what we do in terms of code rationalisation at the start of phase 3.

Goals:
- [x] single version of core files merging in model, simim, satellite and GPM visualisations
- [x] rename files/classes/functions etc. to reflect use of tool beyond SE Asia
- [x] moving file about into more sensible structure reflecting separation of concerns
- [x] consistent structure to the main files of each app
- [x] ensuring  general software engineering principles are applied
- [x] remove redundant apps, code etc.
- [x] check and fix pep8 compliance

**Comment by stevehadd** [comment]
Proposal for repository structure:
root
+- bokeh_apps - containg the various bokeh apps
+- aws - contains aws deployment stuff
+- lib - contains the core code used by the bokeh apps
+- notebooks - possibly a directory to contain example notebooks for development purposes

**Comment by GAndrsn** [comment]
Diagramatic plan for Forest repo structure.

![forest_repo_structure](https://user-images.githubusercontent.com/32956809/35635789-26432458-06a7-11e8-882f-9b823353deef.png)

**Comment by stevehadd** [comment]
This has been done and tested, so closing issue.
