### ISSUE TITLE
Bokeh Axes Labels do not update after region change

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#4]
The bokeh axes are correctly set for the initial plot, but after selecting a region, the axes are not updated to reflect the latitude and longitude ranges of the current plot.

**Comment by GAndrsn** [comment]
Had a go at this, but it's not as simple to correct as I'd hoped. We're not the only ones to have the issue though:

https://github.com/bokeh/bokeh/issues/4014

Will go back to the above thread at some point and pick it up again.

**Comment by GAndrsn** [comment]
Managed to use an alternative approach which scales the image within the existing axes, but the image comes out squashed. Needs work.

**Comment by GAndrsn** [comment]
Images unsquashed. Issue closed.
