### ISSUE TITLE
Bokeh tools icons not displayed

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#5]
When creating a bokeh plot, one can pass a list of tools to the bokeh that should be available to the user, using the tools argument, for example "tools='pan,wheel_zoom,reset'". These do not seem to be present in the bokeh apps in this repository.

**Comment by GAndrsn** [comment]
Try changing 'toolbar_location=None' in the create_bokeh_img_plot_from_fig(self) methods.

**Comment by GAndrsn** [comment]
Looks good. Looks like axis are paired now too. Can this be closed?

**Comment by stevehadd** [comment]
This is working correctly in the version on AWS, so closing ticket.
