### ISSUE TITLE
Display colour legend

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#7]
The bokeh apps do not currently display a colorbar, as the pure matplotlib jupyter did. 

https://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html
https://bokeh.pydata.org/en/latest/docs/reference/models/mappers.html

**Comment by GAndrsn** [comment]
I've been working with an old version of the model vs GPM app, while Stephen does the rationalisation of the apps. I'll apply the following methods to the newly restructured apps.

I've created a function which takes a figure, adds a colorbar, removes the plot axes and saves the colorbar as a PNG.

```
def get_colorbar_from_figure(plot, fig, type_):
    
    """Create and save a colorbar.
    
    """
        
    fig.gca().set_visible(False) 
    fig.set_figwidth(8)
    fig.set_figheight(1)
    cax=plt.axes([0.1, 0.3, 0.8, 0.6])
    cbar = fig.colorbar(plot, cax=cax, orientation='horizontal')

    fig.savefig(os.path.expanduser('~/bokeh_server/model_evaluation_tool/documents/' + \
                                   'plot_sea_model_and_gpm_mpl/static/' + type_ + '_colorbar.png'))
```

The image needs to be saved in the '''static/''' subdirectory of the app, or else the app won't find it. 

The image can then be read into a bokeh Div widget, to appear below the plots:

```
colorbar_src = "\<img src='plot_sea_model_and_gpm_mpl/static/precipitation_colorbar.png'\>"
left_colorbar_div = bokeh.models.widgets.Div(text = colorbar_src, height = 100, width = 800)
right_colorbar_div = bokeh.models.widgets.Div(text = colorbar_src, height = 100, width = 800)
```

This function is currently held in lib_sea.py and called from inside ``update_img_plot_from_fig()``, but this could be updated.

```
lib_sea.get_colorbar_from_figure(self.main_plot, self.current_figure, self.current_type)
```

**Comment by GAndrsn** [comment]
Rather than using a function within the main code, I've created a Jupyter Notebook for generating colorbars, as it's not likely that colorbars will be updated that often. The Notebook reads in color functions from forest, generates a colorbar and saves it as a PNG with a user-specified name. 

The remaining steps are then:

- [ ] Create colorbars and move them to the static directory of the model comparison app.
- [ ] Add Div widget for holding colorbar in model comparison app.
- [ ] Set the app to read in a colorbar into the correct widget.
- [ ] Set the app to switch colorbars when switching variables.

**Comment by GAndrsn** [comment]
The colorbar functionality now works in Two Model Comparison app, but only for precipitation and temperature, purely because I have not copied the relevant colorbar PNG files to the app's ``static/`` directory. Once this is done, I will copy across the functionality to the other apps.

**Comment by GAndrsn** [comment]
All colorbars now added to ``static/`` directory of Two Model Comparison app. Needs restart to check functionality.

**Comment by GAndrsn** [comment]
Basic legends added for all plots, issue closed.
