### ISSUE TITLE
Basic stats display

### ISSUE THREAD

**Issue by stevehadd** [met-office-lab/model_evaluation_tool#8]
Current bokeh apps are missing a key feature from Malcolm Brooks website, which is a small section of text underneath the plot with stats for the plot displayed. This could easily be implemented using the bokeh paragraph widget.
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#paragraph

**Comment by GAndrsn** [comment]
Was this issue resolved, and can it be closed?

**Comment by stevehadd** [comment]
I wasn't sure if wanted stats for any of the other apps. Now that the model v gpm app uses the common plotting class, one of us can easily add the stats to that app if you think thats a good idea. Not sure whether stats make sense for simim vs satellite?

**Comment by GAndrsn** [comment]
Stats as they are are fine, issue closed.
